<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MailHelper.ViewModels</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MailHelper.Core\MailHelper.Core.csproj" />
    <ProjectReference Include="..\MailHelper.Core.Services\MailHelper.Core.Services.csproj" />
    <ProjectReference Include="..\MailHelper.Infrastructure\MailHelper.Infrastructure.csproj" />
  </ItemGroup>

</Project>
