// <auto-generated />
using System;
using MailHelper.Infrastructure.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailHelper.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(MailHelperDbContext))]
    [Migration("20260926111334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AzureClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("azure_client_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.ClassificationFeedbackEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("NewCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_category");

                    b.Property<int?>("NewImportance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_importance");

                    b.Property<string>("OldCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_category");

                    b.Property<int?>("OldImportance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("old_importance");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("classification_feedback", (string)null);
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.MessageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<string>("BodyPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_path");

                    b.Property<string>("BodyPreview")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_preview");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("other")
                        .HasColumnName("category");

                    b.Property<long?>("ClassifiedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("classified_at_utc");

                    b.Property<string>("ClassifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("rule")
                        .HasColumnName("classified_by");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("FromAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("from_address");

                    b.Property<string>("FromName")
                        .HasColumnType("TEXT")
                        .HasColumnName("from_name");

                    b.Property<bool>("HasAttachments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("has_attachments");

                    b.Property<int>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2)
                        .HasColumnName("importance");

                    b.Property<string>("InternetMessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("internet_message_id");

                    b.Property<bool>("IsDeletedRemote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted_remote");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<long>("ReceivedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("RemoteChangeKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_change_key");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_messages_pending_class")
                        .HasFilter("classified_at_utc IS NULL");

                    b.HasIndex("FromAddress")
                        .HasDatabaseName("idx_messages_from");

                    b.HasIndex("AccountId", "ReceivedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_messages_account_received");

                    b.HasIndex("AccountId", "Category", "Importance", "ReceivedAtUtc")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("idx_messages_account_cat_imp");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.NotificationLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<long>("SentAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sent_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("notification_log", (string)null);
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.RuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BuiltinVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("builtin_version");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<int?>("ImportanceHint")
                        .HasColumnType("INTEGER")
                        .HasColumnName("importance_hint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<long?>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.SyncStateEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT")
                        .HasColumnName("account_id");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("TEXT")
                        .HasColumnName("delta_link");

                    b.Property<string>("ImapUidWatermark")
                        .HasColumnType("TEXT")
                        .HasColumnName("imap_uid_watermark");

                    b.Property<long?>("LastSyncAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_sync_at_utc");

                    b.Property<string>("LastSyncStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_sync_status");

                    b.HasKey("AccountId");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.ClassificationFeedbackEntity", b =>
                {
                    b.HasOne("MailHelper.Infrastructure.Storage.MessageEntity", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.MessageEntity", b =>
                {
                    b.HasOne("MailHelper.Infrastructure.Storage.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.NotificationLogEntity", b =>
                {
                    b.HasOne("MailHelper.Infrastructure.Storage.MessageEntity", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MailHelper.Infrastructure.Storage.SyncStateEntity", b =>
                {
                    b.HasOne("MailHelper.Infrastructure.Storage.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
